### PR TITLE
WIP MGMT-17250 Replace xinetd with firewallcmd port forwards

### PR DESCRIPTION
**Pull request by vrutkovs**
xinetd is not available on RHEL9, so services need to be port-forwarded with firewallcmd.

TODO:
* [ ] Fix `kill_port_forwardings`
* [ ] Test ipv6

### CODE REVIEW

**Comment by danmanor** [comment]
@vrutkovs I guess most jobs will not pass as `openshift-tests` will fail, did you tested it works locally ?

**Comment by vrutkovs** [comment]
>did you tested it works locally

No, I don't have the hardware for this. My plan is:
* ensure e2e tests pass on rhel8
* run test with rhel9 via cluster bot to find rhel9-specific issues

**Comment by danmanor** [comment]
@vrutkovs I will try as well with RHEL9

**Comment by danmanor** [comment]
@vrutkovs 
```
make destroy
.
.
.
scripts/utils.sh kill_port_forwardings 'assisted-installer'
usage: 'firewall-cmd --help' for usage information or see firewall-cmd(1) man page
firewall-cmd: error: unrecognized arguments: --remove-forward-ports
usage: 'firewall-cmd --help' for usage information or see firewall-cmd(1) man page
firewall-cmd: error: unrecognized arguments: --remove-forward-ports
usage: 'firewall-cmd --help' for usage information or see firewall-cmd(1) man page
firewall-cmd: error: unrecognized arguments: --remove-forward-ports
```

**Comment by danmanor** [comment]
@vrutkovs  Also 
```
make run
.
.
.
+ echo 'Verifying URL and port are accessible'
Verifying URL and port are accessible
+ url_reachable http://10.1.178.29:6000
+ curl -s http://10.1.178.29:6000 --max-time 4
+ return 7
+ echo 'Sleeping for 2 seconds'
Sleeping for 2 seconds
+ sleep 2s
+ '[' 11 -eq 0 ']'
+ RETRIES=10
+ echo 'Running given function'
Running given function
+ spawn_port_forwarding_command assisted-service 6000 assisted-installer 0 /root/.kube/config minikube undeclared 8090
+ service_name=assisted-service
+ external_port=6000
+ namespace=assisted-installer
+ namespace_index=0
+ kubeconfig=/root/.kube/config
+ target=minikube
+ ip=undeclared
+ port=8090
+ '[' minikube = minikube ']'
++ kubectl --kubeconfig=/root/.kube/config get nodes '-o=jsonpath={.items[0].status.addresses[0].address}'
+ ip=192.168.39.184
+ '[' -z 8090 ']'
++ kubectl --kubeconfig=/root/.kube/config get svc/assisted-service -n assisted-installer '-o=jsonpath={.spec.ports[?(@.port==8090)].nodePort}'
+ port=31610
+ sudo firewall-cmd --zone=public --add-forward-port=port=6000:proto=tcp:toport=31610:toaddr=192.168.39.184
Warning: ALREADY_ENABLED: '6000:tcp:31610:192.168.39.184' already in 'public'

**Comment by danmanor** [comment]
@vrutkovs I have an environment with RHEL9.3 ifyou want to tests

**Pull request closed without merging**
