### PR TITLE
[WIP] Allow creating VMs with emulated TPM device

### PR DESCRIPTION
**Pull request by mkowalski**

### CODE REVIEW

**Comment by osherdp** [comment]
we might have a dupe :)

**Comment by osherdp** [comment]
https://github.com/openshift/assisted-test-infra/pull/1142

**Comment by mkowalski** [comment]
> we might have a dupe :)

Ahh, I see now. Just added a comment there as I see it uses much more complicated way. I will hold on this one and let's try pushing the #1142 forward

**Comment by osherdp** [comment]
> > we might have a dupe :)
> 
> Ahh, I see now. Just added a comment there as I see it uses much more complicated way. I will hold on this one and let's try pushing the #1142 forward

@mkowalski I cannot find your comment
did you push it yet? :)

**Comment by mkowalski** [comment]
> > > we might have a dupe :)
> > 
> > 
> > Ahh, I see now. Just added a comment there as I see it uses much more complicated way. I will hold on this one and let's try pushing the #1142 forward
> 
> @mkowalski I cannot find your comment did you push it yet? :)

I see it when going directly to https://github.com/openshift/assisted-test-infra/pull/1142/files#diff-bc091dbc4c76382ace5163ed25342f2013ea93770784ccaf748d5f79d8ad869d

**Comment by osherdp** [comment]
> > > > we might have a dupe :)
> > > 
> > > 
> > > Ahh, I see now. Just added a comment there as I see it uses much more complicated way. I will hold on this one and let's try pushing the #1142 forward
> > 
> > 
> > @mkowalski I cannot find your comment did you push it yet? :)
> 
> I see it when going directly to https://github.com/openshift/assisted-test-infra/pull/1142/files#diff-bc091dbc4c76382ace5163ed25342f2013ea93770784ccaf748d5f79d8ad869d

no, I cannot see it
maybe it's on "pending" status

**Comment by eliorerz** [comment]
@mkowalski @osherdp Is that PR still needed?

**Comment by osherdp** [comment]
I don't think so, already have been done
/close

**Pull request closed without merging**
