### PR TITLE
Remove OCP deploy mode, which isn't really in use

### PR DESCRIPTION
**Pull request by osherdp**
All of this code is just dead-code which is not used anywhere in any CI process, impacting readability of the testing framework.
This should remove some makefile arguments + targets, remove some script files, and simplify other areas of code that now have to worry about one less deployment case.

### CODE REVIEW

**Review by eliorerz — APPROVED** [review]
LGTM

**Comment by romfreiman** [comment]
are u sure QE not using it?

**Comment by osherdp** [comment]
> are u sure QE not using it?

yes, asked QE https://coreos.slack.com/archives/C016EF00KS5/p1643879673848279

**Pull request merged**
