### PR TITLE
set_dns: skip when base_dns_domains is set

### PR DESCRIPTION
**Pull request by danielerez**
Skip dnsmasq flow when BASE_DNS_DOMAINS env var is set.

### CODE REVIEW

**Comment by tsorya** [comment]
can u explain a little more? How it will work if base domain not set?

**Comment by tsorya** [comment]
i think i got it but can u add this pull request to previous one? and just open one with 2 commits? will be easier to follow

**Comment by danielerez** [comment]
> i think i got it but can u add this pull request to previous one? and just open one with 2 commits? will be easier to follow

I'm just checking whether the env var was defaulted to an empty string in Makefile (i.e. was not defined).
But sure, added to https://github.com/openshift/assisted-test-infra/pull/35.

**Pull request merged**
