### PR TITLE
NO-ISSUE: Fix collect_kube_api_resources to get all CRs in the array

### PR DESCRIPTION
**Pull request by eranco74**

### CODE REVIEW

**Comment by eranco74** [comment]
Artifacts look good:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_assisted-test-infra/1343/pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-capi/1477591696140144640/artifacts/e2e-metal-assisted-capi/baremetalds-assisted-gather/artifacts/

The capi test is flakey and being handled in another [pr](https://github.com/openshift/cluster-api-provider-agent/pull/20)

**Review by osherdp — APPROVED** [review]

**Pull request merged**
