### PR TITLE
Add support for disk tunning - rate and iops

### PR DESCRIPTION
**Pull request by bkopilov**
Libvirt allow to limit disks io and rates per disk name Added support to controller node ,it will allow us to slow down installation by limit disks speed or io.
On every installation phase we may limit disk and undo.

### CODE REVIEW

**Comment by bkopilov** [comment]
@eifrach  , @danmanor

**Comment by eifrach** [comment]
releated to #2365
will be reviewed togther

**Comment by bkopilov** [comment]
Code will be moved to downstream

**Pull request closed without merging**
