### PR TITLE
NO-ISSUE: collect the pod yaml of all the pods running in the same namespace as the capi provider agent

### PR DESCRIPTION
**Pull request by eranco74**

### CODE REVIEW

**Review by osherdp — APPROVED** [review]
/hold
(to inspect job artifacts)

**Comment by eranco74** [comment]
artifacts looks good


> /hold (to inspect job artifacts)

artifacts looks good
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_assisted-test-infra/1670/pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-capi/1532264430912409600/artifacts/e2e-metal-assisted-capi/assisted-baremetal-gather/artifacts/clusters-test-infra-cluster-c5ece150
/unhold

**Pull request merged**
