### PR TITLE
MGMT-8363 - Join flaky tests results on prow spyglass

### PR DESCRIPTION
**Pull request by eliorerz**
Currently, errors on assisted-service logs are shown as separate JUNIT test-case, causing PROW to "split" each test case to new row under `Flaky` section (multiple entries in the Flaky table)
Here instead of 17 lines of failures on `github.com/openshift/assisted-service/internal/controller/controllers.(*ClusterDeploymentsReconciler).Reconcile` with the error `error setting owner reference`, we can see it under single table entry (as single string) without the need to expand multiple entries.
image

### CODE REVIEW

**Comment by osherdp** [comment]
interestingly it doesn't follow ``black`` format
we disclosed scripts from being linted with this format? (not that I think it's critical, just asking)

**Comment by osherdp** [comment]
@eliorerz please add a pic to the PR description, when you have one

**Review by osherdp — APPROVED** [review]

**Comment by eliorerz** [comment]
> interestingly it doesn't follow `black` format we disclosed scripts from being linted with this format? (not that I think it's critical, just asking)

Currently scripts are excluded from being formatted and to be checked by flake8
https://github.com/openshift/assisted-test-infra/blob/36ff2155de88fae0de3c2c3c1d443c7faa74f6a9/Makefile#L28

**Review by osherdp — APPROVED** [review]

**Pull request merged**
