### PR TITLE
[release-ocm-2.5] NO-ISSUE - Prevent tests from being skipped when test parameterized is empty

### PR DESCRIPTION
**Pull request by eliorerz**
Backport of https://github.com/openshift/assisted-test-infra/pull/1824

/cc @osherdp

### CODE REVIEW

**Comment by eliorerz** [comment]
@osherdp Failures doesn't seems related

**Comment by osherdp** [comment]
> @osherdp Failures doesn't seems related

can you override all non-relevant jobs?

**Review by osherdp — APPROVED** [review]
just to make sure it will not retest without any ending to it:
/hold

**Comment by eliorerz** [comment]
@osherdp I think we can merge this, WDYT?

**Comment by osherdp** [comment]
yes, it looks good (other than that now we're failing the two tests in the kube-api job, previously it was just one)

**Comment by eliorerz** [comment]
> yes, it looks good (other than that now we're failing the two tests in the kube-api job, previously it was just one)

I think it was both of them even before on 2.5. Only on master and 2.6 IPv6 failed

**Comment by eliorerz** [comment]
/override ci/prow/e2e-metal-assisted-capi ci/prow/e2e-metal-assisted-kube-api-net-suite

**Pull request merged**
