### PR TITLE
MGMT-4604 Fix scality ephemeral storage error

### PR DESCRIPTION
**Pull request by empovit**
Increase minikube disk allocation so that the VM
has enough space for minikube components and ephemeral storage.

### CODE REVIEW

**Comment by osherdp** [comment]
@empovit you think this will help?
The error message says something about getting to some number of kilobytes, whereas it's limited by 0

**Comment by empovit** [comment]
> @empovit you think this will help?
> The error message says something about getting to some number of kilobytes, whereas it's limited by 0

Yes I do. "0" means not limited, so it gets to the limit (or rather threshold) of total of ephemeral storage available on the node.

**Comment by osherdp** [comment]
/lgtm
OK, great

**Pull request merged**
