### PR TITLE
MGMT-11712: Gather logs using sos report on nodes

### PR DESCRIPTION
**Pull request by vrutkovs**
Use sos report along with toolbox to gather the logs from cluster
nodes.

https://github.com/openshift/assisted-test-infra/pull/1929 + feedback addressed

### CODE REVIEW

**Comment by vrutkovs** [comment]
/hold

Not sure if this would reliably work with disconnected

**Comment by vrutkovs** [comment]
/hold cancel

SOS report now has standard format

**Comment by vrutkovs** [comment]
cc @eliorerz 

This also changes `is_active` implementation of vsphere/nutanix provider to assume all nodes are up (later on we'll need to use API to determine that, but for now we'll just not receive the sos report if the node is down)

**Review by adriengentil — APPROVED** [review]

**Comment by vrutkovs** [comment]
Right, nutanix will be fixed in https://github.com/openshift/release/pull/35548
/skip

**Pull request merged**
