### PR TITLE
Use Python 3.9 image for local environments

### PR DESCRIPTION
**Pull request by osherdp**
Right after https://github.com/openshift/release/pull/24055, the time has come to officially move to the new image.
/cc @eliorerz

### CODE REVIEW

**Comment by eliorerz** [comment]
Need to install python39 as part of `create_full_environment`

**Review by eliorerz — APPROVED** [review]
LGTM

**Comment by osherdp** [comment]
/override ci/prow/e2e-metal-assisted-kube-api-late-binding-single-node
Way too flaky

**Comment by omertuc** [comment]
This broke skipper, you forgot to update the skipper file to point to the new dockerfile

**Comment by osherdp** [comment]
> This broke skipper, you forgot to update the skipper file to point to the new dockerfile

Sorry about that...
How did you encounter that?

**Comment by omertuc** [comment]
Skipper kept using older `test-infra` image that it had cached even after I ran `skipper build` 

I noticed the image was old because the junit-report inside that image was an older incompatible version with latest infra changes

**Pull request merged**
