### PR TITLE
MGMT-9268: Fix kube-api conformance tests are failing

### PR DESCRIPTION
**Pull request by eliorerz**
/cc @osherdp

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Comment by osherdp** [comment]
/hold
all jobs are broken because of CentOS RPM repos being unreachable

**Comment by osherdp** [comment]
@eliorerz unhold?

**Comment by osherdp** [comment]
this just waist resources, because the nodes are getting deleted at the end and we cannot really do conformance tests against it
so I think the right thing here is to hold until fixing the nodes thing
/hold

**Comment by eliorerz** [comment]
> this just waste resources, because the nodes are getting deleted at the end and we cannot really do conformance tests against it so I think the right thing here is to hold until fixing the nodes thing /hold

Correct me if I'm wrong but IIRC we said that we will hold the conformance tests until we will fix the teardown issue

**Comment by osherdp** [comment]
> > this just waste resources, because the nodes are getting deleted at the end and we cannot really do conformance tests against it so I think the right thing here is to hold until fixing the nodes thing /hold
> 
> Correct me if I'm wrong but IIRC we said that we will hold the conformance tests until we will fix the teardown issue

We changed it to allow situations where no kubeconfig file exists. But once it finds any kubeconfig file, it starts testing the cluster
So we should first make nodes stay up after the test ends, then change kube-api job create the file

**Review by osherdp — APPROVED** [review]

**Pull request merged**
