### PR TITLE
NO-ISSUE - Remove duplicate and wrong get_kubeconfig_path

### PR DESCRIPTION
**Pull request by eliorerz**

### CODE REVIEW

**Review by YuviGold — APPROVED** [review]
LGTM

**Comment by YuviGold** [comment]
/hold
Would like to check assisted-gather works before unholding.

**Comment by lranjbar** [comment]
Is this supposed to solve the errors we are seeing in assisted-gather?

**Comment by YuviGold** [comment]
From the logs it seems that the kubeconfigs can be found. There's still an issue about resolving the api endpoint but let's solve it on a separate PR.
```
++ find /home/assisted/build/kubeconfig -type f
+ for kubeconfig in $(find ${KUBECONFIG} -type f)
+ export 'KUBECTL=kubectl --kubeconfig=/home/assisted/build/kubeconfig/kubeconfig_test-infra-cluster-b250ff51'
+ KUBECTL='kubectl --kubeconfig=/home/assisted/build/kubeconfig/kubeconfig_test-infra-cluster-b250ff51'
++ basename /home/assisted/build/kubeconfig/kubeconfig_test-infra-cluster-b250ff51
+ name=kubeconfig_test-infra-cluster-b250ff51
+ export LOGS_DEST=/tmp/artifacts/new_cluster_kubeconfig_test-infra-cluster-b250ff51
+ LOGS_DEST=/tmp/artifacts/new_cluster_kubeconfig_test-infra-cluster-b250ff51
+ make download_service_logs
./scripts/download_logs.sh download_service_logs
+ NAMESPACE=assisted-installer
+ CLUSTER_ID='""'
+ ADDITIONAL_PARAMS=' --sosreport --must-gather --download-all'
+ KUBECTL='kubectl --kubeconfig=/home/assisted/build/kubeconfig/kubeconfig_test-infra-cluster-b250ff51'
+ LOGS_DEST=/tmp/artifacts/new_cluster_kubeconfig_test-infra-cluster-b250ff51
+ KUBE_CRS=(clusterdeployment infraenv agentclusterinstall agent)
+ download_service_logs
+ mkdir -p /tmp/artifacts/new_cluster_kubeconfig_test-infra-cluster-b250ff51
+ '[' minikube = onprem ']'
+ CRS=node,pod,svc,deployment,pv,pvc
+ '[' no == true ']'
+ kubectl --kubeconfig=/home/assisted/build/kubeconfig/kubeconfig_test-infra-cluster-b250ff51 cluster-info

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: dial tcp: lookup api.test-infra-cluster-b250ff51.redhat.com on 147.75.207.207:53: no such host
make: *** [Makefile:416: download_service_logs] Error 1
```

/unhold

**Pull request merged**
