### PR TITLE
MGMT-16287: Remove_api_vip and ingress_vip

### PR DESCRIPTION
**Pull request by nmagnezi**

### CODE REVIEW

**Review by adriengentil — APPROVED** [review]
Looks good, I would like to see the day2 job pass as well!
/hold

**Review by adriengentil — APPROVED** [review]

**Comment by nmagnezi** [comment]
ci/prow/e2e-metal-assisted-day2 is currently broken:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-test-infra/2311/pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-day2/1729155763168874496

**Pull request merged**
