### PR TITLE
NO-ISSUE - Go back to ocpmetal service index

### PR DESCRIPTION
**Pull request by eliorerz**
Reverting https://github.com/openshift/assisted-test-infra/pull/1469 back to ocpmetal

/cc @eliorerz

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Comment by eliorerz** [comment]
Fixed the index service issue

**Comment by eliorerz** [comment]
/override ci/prow/e2e-metal-assisted-kube-api-late-binding-single-node

**Comment by osherdp** [comment]
/override ci/prow/e2e-metal-single-node-live-iso
nu ma

**Pull request merged**
