### PR TITLE
MGMT-19278: Use multi-arch OCP release images with OPENSHIFT_VERSION configuration

### PR DESCRIPTION
**Pull request by danmanor**
Adjust the correct `cpu_architecture` which should be used for cluster, infraenv creation

### CODE REVIEW

**Comment by danmanor** [comment]
/override ci/prow/e2e-metal-assisted-kube-api-late-binding-single-node

**Comment by danmanor** [comment]
/override ci/prow/e2e-metal-assisted-kube-api-late-binding-single-node

**Comment by danmanor** [comment]
/override ci/prow/e2e-metal-assisted-kube-api-late-binding-single-node

**Comment by danmanor** [comment]
/override ci/prow/e2e-metal-assisted-kube-api-late-binding-single-node

**Comment by eifrach** [comment]
> /override ci/prow/e2e-metal-assisted-kube-api-late-binding-single-node

BTW, this should work now

**Comment by danmanor** [comment]
/override ci/prow/e2e-metal-assisted-kube-api-late-binding-single-node

**Comment by danmanor** [comment]
/override ci/prow/e2e-metal-assisted-kube-api-late-binding-single-node

**Comment by danmanor** [comment]
/override ci/prow/e2e-metal-assisted-kube-api-late-binding-sno-4-18

**Pull request merged**
