### PR TITLE
MGMT-3306 Override the default RELEASE_IMAGE in onprem-environment

### PR DESCRIPTION
**Pull request by sacharya**

### CODE REVIEW

**Review by carbonin — APPROVED** [review]

**Comment by carbonin** [comment]
Looks like this is failing on https://github.com/openshift/assisted-test-infra/pull/280. Will have to push them in the same PR or merge one red it seems.

Also looks like you're hitting the pull secret validation now that we're actually passing the image to test :laughing:

**Comment by carbonin** [comment]
> Also looks like you're hitting the pull secret validation now that we're actually passing the image to test 

That said, I'm not sure why the pull secret we pass would be different between for on-prem...

**Comment by carbonin** [comment]
Found the issue. You also need to pass the env `PUBLIC_CONTAINER_REGISTRIES` through to the service.

**Review by carbonin — APPROVED** [review]

**Comment by rwsu** [comment]
ci/prow/e2e-metal-assisted-onprem failed because discovery was broken by https://github.com/openshift/assisted-service/pull/774. 

https://github.com/openshift/assisted-service/pull/810 will fix discovery.

**Review by rwsu — APPROVED** [review]
This PR plus https://github.com/openshift/assisted-service/pull/810/ fixes onprem test-infra.

**Review by YuviGold — APPROVED** [review]

**Pull request merged**
