### PR TITLE
MGMT-2992 support Prometheus UI port forwarding

### PR DESCRIPTION
**Pull request by nmagnezi**

### CODE REVIEW

**Comment by nmagnezi** [comment]
/hold
testing

**Comment by nmagnezi** [comment]
/unhold
Tested OK.

`# make deploy_monitoring`

Ends with:

```
deploy_prometheus_ui.sh: Starting port forwarding for deployment/prometheus-k8s on port 9091
Running given function
Sleeping for 30 seconds
Verifying URL and port are accessible
deploy_prometheus_ui.sh: Prometheus UI can be reached at http://<IP_ADDR_HERE>:9091
deploy_prometheus_ui.sh: Done
make[1]: Leaving directory '/home/test/assisted-test-infra'
```

Prometheus UI works as expected.

**Review by YuviGold — APPROVED** [review]

**Pull request merged**
