### PR TITLE
NO-ISSUE - Fix random tests names while parsing assisted logs and events

### PR DESCRIPTION
**Pull request by eliorerz**
Test cases and suites random names are causing explosive test growth in tooling, sippy and more

/cc @osherdp

### CODE REVIEW

**Comment by eliorerz** [comment]
/hold 
Wait for junit reports

**Review by osherdp — APPROVED** [review]

**Comment by dgoodwin** [comment]
Still some things in the jobs run for this PR that I'm a little worried about:

assisted-logs: "github.com/openshift/assisted-service/internal/controller/controllers.(*ClusterDeploymentsReconciler).Reconcile"
^ is there any way to get this to a more readable version consistent with the rest of openshift ci (text description of the test). Looking at this you can't really see what the test does. I'm concerned primarily about the special characters in it. It's workable, but I'd pitch improvement if possible.

InfraEnv.generate_and_download_infra_env: download_image[openshift_version=4.10]
^ we have a lot of tooling that assumes jobs are separated based on openshift version, which helps categorize them in both testgrid and sippy with release number in the job name.

0075f851-545b-42d4-b2a8-bdf24c9051fa: 0075f851-545b-42d4-b2a8-bdf24c9051fa
^ still showing up in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-test-infra/1567/pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted/1508877982314270720 and I'm assuming that's not good.

Rest is looking good and this is a huge improvement, thanks for the help so quickly.

**Comment by eliorerz** [comment]
> 0075f851-545b-42d4-b2a8-bdf24c9051fa: 0075f851-545b-42d4-b2a8-bdf24c9051fa
> ^ still showing up in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-test-infra/1567/pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted/1508877982314270720 and I'm assuming that's not good.

Will be fixed on https://github.com/openshift/assisted-test-infra/pull/1580



> InfraEnv.generate_and_download_infra_env: download_image[openshift_version=4.10]
> ^ we have a lot of tooling that assumes jobs are separated based on openshift version, which helps categorize them in both testgrid and sippy with release number in the job name.

We sometimes run the same test (e.g. `test_install`) with different openshift versions on the same job

**Comment by dgoodwin** [comment]
> > InfraEnv.generate_and_download_infra_env: download_image[openshift_version=4.10]
> > ^ we have a lot of tooling that assumes jobs are separated based on openshift version, which helps categorize them in both testgrid and sippy with release number in the job name.
> 
> We sometimes run the same test (e.g. `test_install`) with different openshift versions on the same job

I would recommend you separate that into a separate job. You're aggregating up through a 4.11 dashboard https://testgrid.k8s.io/redhat-openshift-ocp-release-4.11-informing#periodic-ci-openshift-release-master-nightly-4.11-e2e-metal-assisted so it's very abnormal to run 4.10 openshift tests in that regard, I'm not entirely sure what might break or get blocked for whom. It's definitely non-standard and I'm not aware of any other jobs doing this.

**Comment by osherdp** [comment]
> > > InfraEnv.generate_and_download_infra_env: download_image[openshift_version=4.10]
> > > ^ we have a lot of tooling that assumes jobs are separated based on openshift version, which helps categorize them in both testgrid and sippy with release number in the job name.
> > 
> > 
> > We sometimes run the same test (e.g. `test_install`) with different openshift versions on the same job
> 
> I would recommend you separate that into a separate job. You're aggregating up through a 4.11 dashboard https://testgrid.k8s.io/redhat-openshift-ocp-release-4.11-informing#periodic-ci-openshift-release-master-nightly-4.11-e2e-metal-assisted so it's very abnormal to run 4.10 openshift tests in that regard, I'm not entirely sure what might break or get blocked for whom. It's definitely non-standard and I'm not aware of any other jobs doing this.

I think @eliorerz meant we have assisted-service presubmit jobs that are installing multiple openshift versions
For the release-controller jobs we should only install the relevant payload and nothing else

We can probably remove those "4.11" appearances from the 4.11 informing jobs' jUnit. @dgoodwin do you think it's critical (or beneficial) to do so?

**Comment by dgoodwin** [comment]
I don't think critical (I'll check with team today), but definitely a good idea, would prefer anything under 4.11 testgrid/sippy/bigquery be specific to 4.11 or upgrading to 4.11.

**Pull request merged**
