### PR TITLE
MGMT-19248: Add OpenShift AI operator

### PR DESCRIPTION
**Pull request by jhernand**
This patch adds the OpenShift AI OLM operator.

Related: https://issues.redhat.com/browse/MGMT-19248
Related: https://issues.redhat.com/browse/MGMT-19056

### CODE REVIEW

**Comment by jhernand** [comment]
Thanks for reviewing @eifrach. I am not in the owner list, so this isn't automatically approved, can you approve it?

**Comment by eifrach** [comment]
> Thanks for reviewing @eifrach. I am not in the owner list, so this isn't automatically approved, can you approve it?
/approve

**Review by eifrach — APPROVED** [review]

**Pull request merged**
