### PR TITLE
NO-ISSUE - Set python3.9 as the python environment default version

### PR DESCRIPTION
**Pull request by eliorerz**
/cc @osherdp

### CODE REVIEW

**Review by osherdp — CHANGES_REQUESTED** [review]
I think this might be what breaks ``dnf`` and other python CLI tools of the OS
It might be dependent on the specific OS (because Fedora / CentOS / RHEL might default to different Pythohn versions) but it's worth making sure we don't break anything

**Comment by eliorerz** [comment]
@osherdp I'm looking in to it locally, no need to retest again

**Comment by eliorerz** [comment]
Not working on RHEL 8.2. Not prioritized for now.

**Pull request closed without merging**
