### PR TITLE
[release-ocm-2.4] MGMT-9102: Backport - Add logic to detect if running in Openshift CI assisted-service PR

### PR DESCRIPTION
**Pull request by eliorerz**
Backport of https://github.com/openshift/assisted-test-infra/pull/1197 

/cc @osherdp @lranjbar

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Review by lranjbar — APPROVED** [review]

**Comment by osherdp** [comment]
/hold
jobs still broken, even with this change

**Comment by lranjbar** [comment]
/lgtm

These errors aren't related. Unhold when ready for merge

**Comment by osherdp** [comment]
/hold
This just seems to waste resources, override / fix might be needed here

**Comment by eliorerz** [comment]
/override ci/prow/e2e-metal-assisted-kube-api 
/override ci/prow/e2e-metal-assisted-kube-api-late-binding-single-node
/override ci/prow/e2e-metal-assisted-none-ipv6

**Pull request merged**
