### PR TITLE
Remove minikube profile

### PR DESCRIPTION
**Pull request by YuviGold**
We do not take advantage of the minikube profile feature at all.
In addition, we would like to drop minikube support.

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Comment by osherdp** [comment]
/hold
way too much spam

**Comment by YuviGold** [comment]
Sorry about that. It requires for https://github.com/openshift/assisted-service/pull/1336#issuecomment-810076070 to get merged first.

**Review by osherdp — APPROVED** [review]

**Review by osherdp — APPROVED** [review]

**Pull request merged**
