### PR TITLE
MGMT-4274 Use AUTH_TYPE flag over ENABLE_AUTH

### PR DESCRIPTION
**Pull request by carbonin**
This will allow us to test new auth types
Removes the flag from the line to update_assisted_service_cm.py
as ENABLE_AUTH wasn't in the list of relevant env vars.

cc @YuviGold is there anywhere else that needs to change for this?
Do we have other automation somewhere that enables auth?

### CODE REVIEW

**Comment by carbonin** [comment]
/hold

Depends on https://github.com/openshift/assisted-service/pull/1201

**Review by YuviGold — APPROVED** [review]
LGTM

**Comment by YuviGold** [comment]
Prow and Jenkins aren't using this var. they both use the defaults.

**Comment by carbonin** [comment]
openshift/assisted-service#1201 was merged so un-holding this.

/hold cancel

**Pull request merged**
