### PR TITLE
NO-ISSUE: better handle pull secret or file of pull secret

### PR DESCRIPTION
**Pull request by eifrach**

### CODE REVIEW

**Comment by adriengentil** [comment]
looks good, can you add a word about this new env var in the README? https://github.com/openshift/assisted-test-infra?tab=readme-ov-file#prerequisites

**Comment by eifrach** [comment]
> Looks good! can you add a word about this new env var in the README? https://github.com/openshift/assisted-test-infra?tab=readme-ov-file#prerequisites

you have it already - I just moved it to to the python code instead of the make file 
here
https://github.com/openshift/assisted-test-infra/blob/master/README.md?plain=1#L67-L68
and here
https://github.com/openshift/assisted-test-infra/blob/master/README.md?plain=1#L174

**Review by adriengentil — APPROVED** [review]

**Comment by adriengentil** [comment]
> you have it already - I just moved it to the python code instead of the Makefile

I'm blind :sweat_smile:

**Comment by eifrach** [comment]
/override ci/prow/e2e-metal-assisted-kube-api-late-binding-single-node

**Pull request merged**
