### PR TITLE
Use latest minikube and kubectl releases

### PR DESCRIPTION
**Pull request by iranzo**
Use latest minikube and kubectl according to their website

### CODE REVIEW

**Comment by YuviGold** [comment]
My fear with "latest" is that API could get broken from time to time. Happened to us with [terraform](https://github.com/openshift/assisted-test-infra/pull/83).

**Comment by iranzo** [comment]
> My fear with "latest" is that API could get broken from time to time. Happened to us with [terraform](https://github.com/openshift/assisted-test-infra/pull/83).

For kubelet is the one labelled as stable, but for minikube didn't  found it :/

**Comment by YuviGold** [comment]
Using [arkade](https://github.com/alexellis/arkade) for `minikube` and `kubectl` installation since https://github.com/openshift/assisted-test-infra/pull/660

**Pull request closed without merging**
