### PR TITLE
NO-ISSUE: run CI in kube-api mode for e2e tests

### PR DESCRIPTION
**Pull request by RazRegev**

### CODE REVIEW

**Review by osherdp — APPROVED** [review]
/lgtm

**Comment by YuviGold** [comment]
I'm not sure what is the outcome of this operation. Would we want always to run in kubeapi mode?

**Comment by RazRegev** [comment]
> I'm not sure what is the outcome of this operation. Would we want always to run in kubeapi mode?

yes, like we do in aws ci

**Pull request merged**
