### PR TITLE
Get libvirt domain mac and ip from agent instead of lease

### PR DESCRIPTION
**Pull request by nshidlin**
Static IP flow was broken by https://github.com/openshift/assisted-test-infra/pull/960/files
Currently libvirt node's IP and mac are taken from dhcp lease file. In the case of static IP this list is empty. This PR queries libvirt agent for addresses instead of the dhcp leases

### CODE REVIEW

**Comment by osherdp** [comment]
@nshidlin can you take a look afterwards to see if sosreports are still generated properly?
because I think they depend on the same code

**Comment by nshidlin** [comment]
> @nshidlin can you take a look afterwards to see if sosreports are still generated properly?
> because I think they depend on the same code

So, basically see that the nodes can be ssh'd into with `run_command`?

**Comment by osherdp** [comment]
@nshidlin you can also look at the artifacts of ``e2e-metal-assisted``, we should have it in a directory named ``sosreport``

**Comment by osherdp** [comment]
but yes, that would work also I think

**Review by osherdp — APPROVED** [review]

**Comment by osherdp** [comment]
@nshidlin why did you close it?

**Pull request closed without merging**
