### PR TITLE
gather bootkube, kubelet and crio service logs

### PR DESCRIPTION
**Pull request by osherdp**
/cc @YuviGold @tsorya @ori-amizur

### CODE REVIEW

**Review by YuviGold — APPROVED** [review]

**Comment by tsorya** [comment]
so needed change, thanks a lot

**Comment by YuviGold** [comment]
> /test e2e-metal-assisted-none-ipv6

BTW, it never passed

**Comment by osherdp** [comment]
> > /test e2e-metal-assisted-none-ipv6
> 
> @osherdp BTW, it never passed

I know, that's why I ran it :)

**Pull request merged**
