### PR TITLE
discovery: custom cluster name when domain specified

### PR DESCRIPTION
**Pull request by danielerez**
Handle custom cluster name when 'base-dns-domains' is specified
(cluster_name + random_postfix).

### CODE REVIEW

**Comment by tsorya** [comment]
@danielerez it will break set_dns 
https://github.com/openshift/assisted-test-infra/blob/master/scripts/assisted_deployment.sh#L7

**Comment by tsorya** [comment]
we need to handle it before pushing

**Comment by danielerez** [comment]
> set_dns will not work

right, fixed here: https://github.com/openshift/assisted-test-infra/pull/37

**Pull request merged**
