### PR TITLE
NO-ISSUE: Update to python 3.12

### PR DESCRIPTION
**Pull request by adriengentil**

### CODE REVIEW

**Comment by adriengentil** [comment]
Hi @bkopilov,  any concerns about this change?

**Comment by bkopilov** [comment]
> Hi @bkopilov, any concerns about this change?

Why do we need to change python version to 3.12 ?  

> Hi @bkopilov, any concerns about this change?

**Comment by adriengentil** [comment]
>Why do we need to change python version to 3.12 ?
to keep things updated and avoid to much gaps between versions upgrades

**Review by eifrach — APPROVED** [review]

**Pull request merged**
