### PR TITLE
NO-ISSUE: Test CI - TPMv2 job

### PR DESCRIPTION
**Pull request by nmagnezi**

### CODE REVIEW

**Comment by eliorerz** [comment]
@nmagnezi Do you still need this PR?

**Comment by nmagnezi** [comment]
> @nmagnezi Do you still need this PR?

Nop. Needed that to test [ci/prow/e2e-metal-assisted-tpmv2](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-test-infra/1309/pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-tpmv2/1471549487678754816).
All tests passed so I'm closing this PR.

**Pull request closed without merging**
