### PR TITLE
MGMT-15018: Add option to mark variable origin

### PR DESCRIPTION
**Pull request by eliorerz**
We currently can only differ if variable is set as environment variable or not.
This PR add the option to know the origin of a variable - where it was set

### CODE REVIEW

**Review by adriengentil — APPROVED** [review]
Looks good! Jous curious, what is the use case for that?

**Comment by eliorerz** [comment]
> Hey suggestion , ( your code worked for me but may i suggesst something ? )

The main issue here is that triggerable set should be protected while config set should not, when we join those two we basically allowing anyone to update the global_config which we tried to prevent in the first place.

**Comment by eliorerz** [comment]
> Looks good! Just curious, what is the use case for that?

@adriengentil QE want to prevent override when setting variable using `parametrized` the same as we are doing with environment variables

**Comment by bkopilov** [comment]
> > Hey suggestion , ( your code worked for me but may i suggesst something ? )
> 
> The main issue here is that triggerable set should be protected while config set should not, when we join those two we basically allowing anyone to update the global_config which we tried to prevent in the first place. Also, the `_keys_origin` cannot be class member and need to be initialized as part of object initialization

Ack .
why `_keys_origin` cannot be class member   ??  i dont understand.  we hold  a trigger status for variable and we dont care what object is calling ??

**Comment by eliorerz** [comment]
> why _keys_origin cannot be class member ?? i dont understand. we hold a trigger status for variable and we dont care what object is calling ?? It will allow us to mainain _keys_origin for all object created and it wont depends of its type object.

Because `parameterized` is "working" on instance of a configuration and not all of the configurations the same. Assuming that can cause issues during tests (serial or parallel)

**Comment by eliorerz** [comment]
/override ci/prow/e2e-metal-assisted-kube-api-late-binding-single-node

**Pull request merged**
