### PR TITLE
NO-ISSUE: remove dnf update

### PR DESCRIPTION
**Pull request by tsorya**

### CODE REVIEW

**Review by nmagnezi — COMMENTED** [review]
LGTM. waiting for CI results to approve.

**Comment by eliorerz** [comment]
Why we want to remove the update ?

**Comment by osherdp** [comment]
/test e2e-metal-assisted-tpmv2
/hold
let's hope it works

**Comment by osherdp** [comment]
> /test e2e-metal-assisted-tpmv2 /hold let's hope it works

if not, maybe we can just add ``--refresh`` to the next install command, it should do the trick

**Review by osherdp — APPROVED** [review]

**Comment by osherdp** [comment]
It didn't fix the dracut thing:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-test-infra/1324/pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-kube-api-late-binding-single-node/1473248901258547200

But either way it's a good idea to merge it

**Comment by osherdp** [comment]
again, not fixing the problem but an improvement nonetheless 
/unhold

**Pull request merged**
