### PR TITLE
MGMT-4638 Rename `Group/Version` to `agent-install.openshift.io/v1beta1`

### PR DESCRIPTION
**Pull request by nmagnezi**

### CODE REVIEW

**Comment by nmagnezi** [comment]
/hold
pending on https://github.com/openshift/assisted-service/pull/1363

**Comment by filanov** [comment]
@nmagnezi @RazRegev is there any affect on downstream test?

**Comment by RazRegev** [comment]
@nmagnezi have you test it locally with the kube-api flow against your assisted-service patch?

**Comment by nmagnezi** [comment]
> @nmagnezi have you test it locally with the kube-api flow against your assisted-service patch?

will retest when https://github.com/openshift/assisted-service/pull/1363 gets merged to assisted-service

**Review by djzager — APPROVED** [review]

**Comment by osherdp** [comment]
/hold
let's see if it fixes the build

**Pull request merged**
