### PR TITLE
enable a fix_uid.sh script for prow tests

### PR DESCRIPTION
**Pull request by osherdp**
https://github.com/openshift/release/pull/14552#discussion_r551833515

/cc @YuviGold

### CODE REVIEW

**Comment by YuviGold** [comment]
I honestly don't think we should add it.

**Comment by osherdp** [comment]
> I honestly don't think we should add it.

Maybe. But I cannot know why if you won't elaborate... :)

**Comment by YuviGold** [comment]
> > I honestly don't think we should add it.
> 
> Maybe. But I cannot know why if you won't elaborate... :)

Isn't that obvious? ;-)

**Pull request closed without merging**
