### PR TITLE
MGMT-15703: Update vsphere ci machine base image and update packer version

### PR DESCRIPTION
**Pull request by eliorerz**
/cc @adriengentil @osherdp @gamli75

### CODE REVIEW

**Comment by eliorerz** [comment]
/override ci/prow/e2e-metal-assisted-kube-api-late-binding-single-node 
/override ci/prow/e2e-metal-assisted-kube-api-net-suite 
/override ci/prow/e2e-metal-single-node-live-iso

**Review by adriengentil — APPROVED** [review]

**Comment by adriengentil** [comment]
/override ci/prow/e2e-metal-assisted-kube-api-late-binding-single-node
/override ci/prow/e2e-metal-assisted-kube-api-net-suite
/override ci/prow/e2e-metal-single-node-live-iso

**Pull request merged**
