### PR TITLE
Update default DNS domain

### PR DESCRIPTION
**Pull request by vrutkovs**
Change default spoke domain to metalkube.org.
This would let us run proxy step in CI and gather chain to collect more info from
spoke cluster

Related: https://github.com/openshift/release/pull/34411

### CODE REVIEW

**Review by eranco74 — COMMENTED** [review]
/lgtm

**Comment by eranco74** [comment]
Seems that e2e-metal-single-node-live-iso depends on the old default DNS to succeed.
It's probably getting it from [here](https://github.com/openshift/assisted-test-infra/blob/5cfa00374c377154765958779df6d0c4fcd8f626/src/consts/env_defaults.py#L36) 
Or from the configuration in openshift/release

**Comment by vrutkovs** [comment]
/hold

checking if `const` update fixes e2e-metal-single-node-live-iso

**Comment by eranco74** [comment]
/lgtm
/approve
/hold
@vrutkovs since the /todo above the link to the release was never done. please fix openshift/release to set the right DNS so the SNO live ISO job keep passing.
Feel free to unhold   

> Right, its hardcoded in https://github.com/openshift/release/blob/29d1eb75a3ae1457dd8109f3119f4948cce98fe8/ci-operator/step-registry/baremetalds/sno/setup/baremetalds-sno-setup-commands.sh#L50-L51
> 
> /hold cancel

**Comment by vrutkovs** [comment]
Doing that in https://github.com/openshift/release/pull/34740

**Comment by vrutkovs** [comment]
single-node-live-iso testing in https://github.com/openshift/release/pull/34746

**Comment by eliorerz** [comment]
/hold
This PR changes the tests defaults. Need QE approval.
/cc @lalon4

**Comment by lalon4** [comment]
/lgtm
thanks for the update, in our runs we dont use default: https://gitlab.cee.redhat.com/ocp-edge-qe/ocp-edge/-/blob/master/linchpin-workspace/hooks/ansible/ocp-edge-setup/roles/assisted-installer/tasks/assisted-run-functional-api-tests.yaml#L272

**Pull request closed without merging**
