### PR TITLE
NO-ISSUE: Enable sourcing utils.sh in function calls

### PR DESCRIPTION
**Pull request by danmanor**
- enable sourcing utils.sh in function calls
- Fix download_logs url

The logs are collected now -  https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_assisted-test-infra/2576/pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted/1861049718910488576/artifacts/e2e-metal-assisted/assisted-common-gather/artifacts/2024-11-25_15-05-40_85b00325-b4ac-4ec9-bd07-00c1292f2162/

### CODE REVIEW

**Comment by danmanor** [comment]
/override ci/prow/e2e-metal-assisted-kube-api-late-binding-single-node

**Review by adriengentil — APPROVED** [review]

**Pull request merged**
