### PR TITLE
Terraform failed: Removing job_name from the vm name. Adding ansible …

### PR DESCRIPTION
**Pull request by michaellevy101**
…to the images

fixing "expected length of name to be in the range (1 - 80), got assisted-ci-rehearse-26612-pull-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted-1498344731409649664"

### CODE REVIEW

**Comment by omertuc** [comment]
why ansible?

**Comment by michaellevy101** [comment]
> why ansible?
Currently our CI uses bash and ansible. want to try using ansible for some tasks instead of bash. Just opening this option

**Comment by omertuc** [comment]
If it's already using ansible why does it suddenly need to be installed? Why didn't it work before?

**Comment by tsorya** [comment]
lets open the option when it will be really needed.

**Comment by eliorerz** [comment]
>don't see any good reason for blocking this PR because of installing ansible

Regardless this PR, test-infra base image is already containing a lot more functionality than its should

**Comment by michaellevy101** [comment]
> containing
right, It's a huge image need to minimize the image size by reducing layers or breaking to multiple images.
Please note that this image is internal and not use externally by customer or in production

**Pull request merged**
