### PR TITLE
MGMT-13247: Support alternative libvirt URI

### PR DESCRIPTION
**Pull request by adriengentil**
In the scope of the heterogeneous cluster, we must be able to spawn VMs on a remote CI machine. 

This change updates
- `TerraformController`, `LibvirtController` and `LibvirtNetworkAssets` to take a `libvirt_uri`
- `LibvirtNetworkAssets` to take customized `base_asset` in input and skip local gathering of networking data when `libvirt_uri` is not the default one (aka the local one)

### CODE REVIEW

**Comment by adriengentil** [comment]
/cc @osherdp 

/test e2e-metal-assisted-static-ip-suite
flake

**Review by osherdp — APPROVED** [review]

**Pull request merged**
