### PR TITLE
MGMT-4472 - update test infra to use the new REST API for static netw…

### PR DESCRIPTION
**Pull request by yevgeny-shnaidman**
…ork config

### CODE REVIEW

**Comment by osherdp** [comment]
@yevgeny-shnaidman what's this doing?

**Comment by masayag** [comment]
pls fix typo in PR and commit message (s/updata/update)

**Comment by yevgeny-shnaidman** [comment]
> @yevgeny-shnaidman what's this doing?

we are changing a little bit the API and the implementation for static network configuration so that we will be able to support almost any configuration supported by nmstate without additional changes to our code. and this commit aligns the test-infra with the new API

**Comment by masayag** [comment]
LGTM

**Pull request merged**
