### PR TITLE
Fix api_vip for  update_oc_config function

### PR DESCRIPTION
**Pull request by bkopilov**
Added new structure return when SNO node, get_ip_for_single node returns string. In case exception bubbled up we handle it and set "" as address

Fix config_etc_hosts call , changed param to api_vip

### CODE REVIEW

**Comment by bkopilov** [comment]
@lalon4 , @adriengentil

**Comment by lalon4** [comment]
@nmagnezi

**Review by adriengentil — APPROVED** [review]
/ok-to-test

**Review by adriengentil — APPROVED** [review]

**Pull request merged**
