### PR TITLE
Allow overriding pytest flags

### PR DESCRIPTION
**Pull request by osherdp**
Back in https://github.com/openshift/assisted-test-infra/pull/1824 we prevented tests marked with skip to just be skipped (currently they are marked as failures).

The reason we did it is to prevent a situation where the list of openshift versions come off empty and the tests are considered skipped (and passing vacuously).

This enables emptying all pytest ``PYTEST_FLAGS`` to disable this kind of behavior.

/cc @lalon4 @eliorerz

### CODE REVIEW

**Comment by osherdp** [comment]
/hold
to make sure it works

**Comment by osherdp** [comment]
/hold
waiting for ack from qe

**Comment by bkopilov** [comment]
Hi ,  
Tested this code, 
When the param is export PYTEST_FLAGS=""   the test fails... and not skipped
When the param is set to export PYTEST_FLAGS=" " , test skipped as expected

Benny

**Comment by osherdp** [comment]
> Hi , Tested this code, When the param is export PYTEST_FLAGS="" the test fails... and not skipped When the param is set to export PYTEST_FLAGS=" " , test skipped as expected
> 
> Benny

ack. thank you!
/unhold

**Pull request merged**
