### PR TITLE
MGMT-6579: download_logs.sh: collect kube-api CRs

### PR DESCRIPTION
**Pull request by RazRegev**
Collect data and description of cluster deployment, agent cluster install,
InfraEnv, and the agents in kube-api mode.

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_assisted-test-infra/826/pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-kube-api/1396781858645086208/artifacts/e2e-metal-assisted-kube-api/baremetalds-assisted-gather/artifacts/

### CODE REVIEW

**Comment by filanov** [comment]
@RazRegev the test is failed where i can see the CRs? can you please add a link?

**Comment by RazRegev** [comment]
> @RazRegev the test is failed where i can see the CRs? can you please add a link?

it failed because I pushed an irrelevant commit by mistake

**Comment by filanov** [comment]
> > @RazRegev the test is failed where i can see the CRs? can you please add a link?
> 
> it failed because I pushed an irrelevant commit by mistake

Regardless can you make sure that it works? an example of the location

**Comment by RazRegev** [comment]
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_assisted-test-infra/826/pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-kube-api/1396781858645086208/artifacts/e2e-metal-assisted-kube-api/baremetalds-assisted-gather/artifacts/

> > > @RazRegev the test is failed where i can see the CRs? can you please add a link?
> > 
> > 
> > it failed because I pushed an irrelevant commit by mistake
> 
> Regardless can you make sure that it works? an example of the location

**Review by YuviGold — APPROVED** [review]
LGTM

**Comment by filanov** [comment]
Nice

**Pull request merged**
