### PR TITLE
Revert "MGMT-7351 - Move deployment scripts from assisted-service into test-infra scripts"

### PR DESCRIPTION
**Pull request by eliorerz**
Reverts openshift/assisted-test-infra#1262

Currently the deployments scripts are still duplicated we are using them from assisted-service in CI jobs.
This task was postponed to unknown time.

/cc @osherdp

### CODE REVIEW

**Comment by osherdp** [comment]
/hold
(waiting for ``e2e-metal-assisted-kube-api-late-binding-single-node``)

**Review by osherdp — APPROVED** [review]

**Comment by eliorerz** [comment]
> /hold
> (waiting for `e2e-metal-assisted-kube-api-late-binding-single-node`)

It will fail until https://github.com/openshift/assisted-test-infra/pull/1389 will merge

**Review by osherdp — APPROVED** [review]

**Pull request merged**
