### PR TITLE
Use Precommit GitHub Action

### PR DESCRIPTION
**Pull request by iranzo**
Uses pre-commit github action as additional test for validating PR's

### CODE REVIEW

**Comment by tsorya** [comment]
@YuviGold i think we have it in prow right?

**Comment by iranzo** [comment]
> @YuviGold i think we have it in prow right?

Hi, I was talking with @YuviGold  on slack regarding this as the instance seems to be failing in some tests while setting it up (check my prior PR's)

**Comment by iranzo** [comment]
For example: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-test-infra/45/pull-ci-openshift-assisted-test-infra-master-lint/1283741441767510016

**Pull request merged**
