### PR TITLE
MGMT-12442: Use SCSI drives instead of IDE

### PR DESCRIPTION
**Pull request by adriengentil**
ARM VM do not supports IDE/SATA drives, SCSI seems to be a common ground
between x86_64 and ARM machines.

Update bootstrap_in_place as the disk name changed.

### CODE REVIEW

**Comment by adriengentil** [comment]
I did not make it configurable because I'm not sure that it is worth to have this granularity.

**Review by osherdp — APPROVED** [review]

**Comment by adriengentil** [comment]
committed a change in this branch by mistake :man_facepalming:

**Review by osherdp — APPROVED** [review]

**Pull request merged**
