### PR TITLE
NO-ISSUE - Use baremetal platform on SNO

### PR DESCRIPTION
**Pull request by eliorerz**
/cc @tsorya

### CODE REVIEW

**Comment by tsorya** [comment]
failure is relevant to the change 
HTTP response body: {"code":400,"message":"parsing newClusterParams body from \"\" failed, because json: cannot unmarshal string into Go struct field ClusterCreateParams.platform of type models.Platform"}

**Comment by romfreiman** [comment]
why baremetal platfrom? what am i missing? sno is none

**Comment by eliorerz** [comment]
> failure is relevant to the change HTTP response body: {"code":400,"message":"parsing newClusterParams body from "" failed, because json: cannot unmarshal string into Go struct field ClusterCreateParams.platform of type models.Platform"}

Yeah, I missed something there ...

**Comment by tsorya** [comment]
It will set none but in test-infra sno should be treated as baremetal and use baremetal teraform. At least till we will not refactor it

**Comment by eliorerz** [comment]
> why baremetal platfrom? what am i missing? sno is none

Only on test-infra, the cluster is created with `platform_type=none`.
The flow in test infra requires baremetal platfrom for the right terraform configuration.
@tsorya will probably could explain it better but we will deferentially need to change the flow in test infra so we will support SNO  with none platform

**Pull request merged**
