### PR TITLE
Remove multistage, install SERVICE on bring_assisted_service target

### PR DESCRIPTION
**Pull request by YuviGold**

### CODE REVIEW

**Comment by YuviGold** [comment]
/hold
Need to insert the client inside the container

**Review by eranco74 — COMMENTED** [review]
/lgtm

**Comment by eranco74** [comment]
> Need to insert the client inside the container
If the test-infra image require the client pip package let's add it to the requirements.txt

**Comment by YuviGold** [comment]
> > Need to insert the client inside the container

> If the test-infra image require the client pip package let's add it to the requirements.txt

@eranco74 
The problem is that we don't upload a python package to any registry

**Comment by eranco74** [comment]
> > > Need to insert the client inside the container
> 
> > If the test-infra image require the client pip package let's add it to the requirements.txt
> 
> @eranco74
> The problem is that we don't upload a python package to any registry

@YuviGold, @filanov is there a ticket for publishing the assisted-service pip package?

**Comment by filanov** [comment]
> > > > Need to insert the client inside the container
> > 
> > 
> > > If the test-infra image require the client pip package let's add it to the requirements.txt
> > 
> > 
> > @eranco74
> > The problem is that we don't upload a python package to any registry
> 
> @YuviGold, @filanov is there a ticket for publishing the assisted-service pip package?

I remember that we talked about it but i didn't find any related ticket.

**Comment by YuviGold** [comment]
> > > > Need to insert the client inside the container
> > 
> > 
> > > If the test-infra image require the client pip package let's add it to the requirements.txt
> > 
> > 
> > @eranco74
> > The problem is that we don't upload a python package to any registry
> 
> @YuviGold, @filanov is there a ticket for publishing the assisted-service pip package?

In your opinion do we want to upload the package?

**Comment by filanov** [comment]
> > > > > Need to insert the client inside the container
> > > 
> > > 
> > > > If the test-infra image require the client pip package let's add it to the requirements.txt
> > > 
> > > 
> > > @eranco74
> > > The problem is that we don't upload a python package to any registry
> > 
> > 
> > @YuviGold, @filanov is there a ticket for publishing the assisted-service pip package?
> 
> In your opinion do we want to upload the package?

I'm not sure how other services are doing it, QE, test-infra and other people that want to use our python client so if it can help someone i don't mind to publish a client.
The issue is that besides test-infra i'm not sure that other clients will take the right version.

**Comment by YuviGold** [comment]
assisted-service-client is required for everywhere with skipper. This solution won't work.

**Pull request closed without merging**
