### PR TITLE
MGMT-11926: bump vsphere machine specs

### PR DESCRIPTION
**Pull request by vrutkovs**
Add more memory to the cluster machines so that periodic conformance tests would have a better chance of passing.

Todo:
* [ ] Find out why KubeCPUOvercommit is still firing

### CODE REVIEW

**Comment by vrutkovs** [comment]
/test e2e-vsphere-assisted

Seems the test was killed in the middle

**Comment by vrutkovs** [comment]
KubeMemoryOvercommit gone, KubeCPUOvercommit remains

**Review by eliorerz — APPROVED** [review]
LGTM

**Pull request merged**
