### PR TITLE
MGMT-8366 - Download image using url on v1 branch

### PR DESCRIPTION
**Pull request by eliorerz**

### CODE REVIEW

**Comment by eliorerz** [comment]
> @eliorerz: No presubmit jobs available for openshift/assisted-test-infra@v1

@osherdp

**Comment by osherdp** [comment]
> > @eliorerz: No presubmit jobs available for openshift/assisted-test-infra@v1
> 
> @osherdp

hmm, for some reason I thought we opened this branch with prow
let me see if it's easy adding tests here (only real limitation I'm seeing here is working with the matching service branch)

**Comment by osherdp** [comment]
let's see if it works: https://github.com/openshift/release/pull/24063

**Pull request merged**
