### PR TITLE
MGMT-12345: Fix vsphere CI jobs failures due to Internal Server Error (500)

### PR DESCRIPTION
**Pull request by eliorerz**
vsphere based CI jobs are failing with Internal server error when trying to apply the terraform configurations.

```
This field has been renamed to vsphere_server.

(and 2 more similar warnings elsewhere)
 , error 
Error: error 500 Internal Server Error 
```

example:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-test-infra/1885/pull-ci-openshift-assisted-test-infra-master-e2e-vsphere-assisted/1584085582655524864

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Comment by eliorerz** [comment]
`e2e-vsphere-assisted-kube-api` passed on the last execution, retrying ...

/test e2e-vsphere-assisted-kube-api
/test e2e-vsphere-assisted

**Comment by eliorerz** [comment]
It seems that all the failed jobs are failing only on the IBM environment and not the VMc. So it's probably not test-infra/CI configurations issue

**Review by vrutkovs — APPROVED** [review]
/lgtm

**Pull request merged**
