### PR TITLE
Describing kubernetes objects on creation failure

### PR DESCRIPTION
**Pull request by michaellevy101**
The purpose of this PR is to debug the "e2e-metal-assisted-kube-api-late-binding-single-node" flaky test.
Looks like the problem was on the setup stage while deploying the assisted-service pod on the hub cluster (before running the actual test) we didn't find any relevant data, so we added an "oc describe" command to check why the pod couldn't become ready.
https://issues.redhat.com/browse/MGMT-8805

### CODE REVIEW

**Comment by osherdp** [comment]
@michaellevy101 can you please supply some PR description? Also attach Jira tickets if there are any
Thanks in advance!

**Comment by eliorerz** [comment]
This PR is no longer relevant due to  https://github.com/openshift/assisted-test-infra/pull/1395

**Pull request closed without merging**
