### PR TITLE
NO-ISSUE - Remove project path dependency from CI

### PR DESCRIPTION
**Pull request by eliorerz**
Remove addressing test full path during CI.
e.g. https://github.com/openshift/release/blob/745a5b845211206555230dacda43a3f4ac993414/ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml#L645

/cc @osherdp

### CODE REVIEW

**Comment by eliorerz** [comment]
We will no longer have direct access to test-infra path in CI once this is merged https://github.com/openshift/release/pull/24695

**Review by osherdp — APPROVED** [review]

**Comment by eliorerz** [comment]
/override ci/prow/e2e-metal-assisted ci/prow/e2e-metal-assisted-kube-api ci/prow/e2e-metal-assisted-kube-api-late-binding-single-node  ci/prow/e2e-metal-single-node-live-iso

**Comment by eliorerz** [comment]
/override ci/prow/e2e-metal-assisted 
/override ci/prow/e2e-metal-assisted-kube-api 
/override ci/prow/e2e-metal-assisted-kube-api-late-binding-single-node 
/override ci/prow/e2e-metal-single-node-live-iso

**Pull request merged**
