### PR TITLE
MGMT-14094: Fix oci cleanup

### PR DESCRIPTION
**Pull request by adriengentil**
Few changes:
- Fix how credentials are passed
- Exclude `oci_load_balancer_backend_set`, it will be deleted along the
  LB it belongs to
- Improve ansible output

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Review by eliorerz — APPROVED** [review]
LGTM

**Comment by adriengentil** [comment]
/retest
looks like package installations trigger some flakes

**Pull request merged**
