### PR TITLE
Update skipper in download_logs && download_all_logs pipelines

### PR DESCRIPTION
**Pull request by RazRegev**

### CODE REVIEW

**Comment by omertuc** [comment]
> retest

Nooo single-node is not required 😓

**Review by YuviGold — APPROVED** [review]
Nice

**Comment by eranco74** [comment]
@omertuc please change the live-iso to always_run: False

**Comment by omertuc** [comment]
> @omertuc please change the live-iso to always_run: False

https://github.com/openshift/release/pull/16213

**Comment by YuviGold** [comment]
Do we understand why it didn't get merged?

**Comment by omertuc** [comment]
> Do we understand why it didn't get merged?

No idea... but why does it keep restarting everything?

**Review by YuviGold — APPROVED** [review]

**Pull request merged**
