### PR TITLE
NO-ISSUE: Increase libvirt wait for machine IP timeout from 360 to 600

### PR DESCRIPTION
**Pull request by omertuc**
See commit message

### CODE REVIEW

**Review by eliorerz — APPROVED** [review]
LGTM

**Comment by eliorerz** [comment]
@omertuc I'm not sure that what is casing the `Timeout of 360 seconds expired waiting for Waiting for Ips` error but lets give it a try

**Comment by omertuc** [comment]
> @omertuc I'm not sure that what is casing the `Timeout of 360 seconds expired waiting for Waiting for Ips` error but lets give it a try

If you look at sosreport libvirt logs you can see that the machine does have an IP, leading me to believe it's a matter of just needing more time.

This test is different that other tests because it's using a full OCP cluster as hub and installing another cluster as spoke, meaning there are a lot more VMs, so maybe things are a bit slower and we hit this timeout

**Comment by omertuc** [comment]
This did not help...

**Pull request merged**
