### PR TITLE
NO-ISSUE fix typo of metadata file name

### PR DESCRIPTION
**Pull request by osherdp**
/hold
Need to change on assisted-installer-deployment as well

### CODE REVIEW

**Comment by osherdp** [comment]
@omertuc see https://github.com/openshift-assisted/assisted-installer-deployment/pull/62

**Comment by omertuc** [comment]
> @omertuc see [openshift-assisted/assisted-installer-deployment#62](https://github.com/openshift-assisted/assisted-installer-deployment/pull/62)

Yeah saw that, still, I remember seeing it in other places

**Comment by YuviGold** [comment]
> > @omertuc see [openshift-assisted/assisted-installer-deployment#62](https://github.com/openshift-assisted/assisted-installer-deployment/pull/62)
> 
> Yeah saw that, still, I remember seeing it in other places

I am not aware of other places. @oshercc is there something in Elastic?

**Pull request merged**
