### PR TITLE
install podman from 4.0 stream on RHEL 8 machines

### PR DESCRIPTION
**Pull request by osherdp**
Handling several issues related to a QE environment that had an outdated (v2) version of podman:
* When installing podman, use ``--best`` to allow it to upgrade the package if that's possible.
* For RHEL 8, enable ``container-tools:4.0`` in order to be able to install later podman versions than v2.x.

### CODE REVIEW

**Comment by osherdp** [comment]
/hold
waiting for the tests

**Review by eliorerz — APPROVED** [review]
LGTM

**Pull request merged**
