### PR TITLE
MGMT-19236: Add Openshift sandboxed containers operator(OSC) support

### PR DESCRIPTION
**Pull request by pezhang**
- Testing with 3 masters and 3 workers, the osc operator can be installed. 
Screenshot from 2024-12-02 23-32-30

- Testing with SNO, the osc operator can be installed. 
Screenshot from 2024-12-03 10-27-37

### CODE REVIEW

**Comment by pezhang** [comment]
Hello @eifrach Could you help to review this patch again? Thanks a lot.

**Comment by eifrach** [comment]
/retitle MGMT-19236: Add Openshift sandboxed containers operator(OSC) support

**Comment by eifrach** [comment]
/override ci/prow/e2e-metal-assisted-kube-api-late-binding-single-node

**Pull request merged**
