### PR TITLE
WIP: Try to revert 0.7.1 libvirt back to 0.6.14

### PR DESCRIPTION
**Pull request by omertuc**
Trying to track down the root cause of the recent DNS issues we see in [this](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-day2-single-node-periodic) job

### CODE REVIEW

**Comment by adriengentil** [comment]
@omertuc any objections to merge this one? I guess it will take some time to get the fix merged and published upstream.

**Comment by omertuc** [comment]
good point, will open proper revert PR

**Comment by omertuc** [comment]
Opened #2000

**Pull request closed without merging**
