### PR TITLE
MGMT-7230: Add ODF operator in the operatorType

### PR DESCRIPTION
**Pull request by rewantsoni**
Add odf operator to the operatorTypes

Signed-off-by: Rewant Soni <resoni@redhat.com>

Depends on: https://github.com/openshift/assisted-service/pull/2932

### CODE REVIEW

**Comment by lalon4** [comment]
Need to think how to merge it. we are using test-infra master branch to run tests against Staging and Integration, so it means we will break staging tests

**Comment by eliorerz** [comment]
I think you need to rebase

**Comment by rewantsoni** [comment]
> I think you need to rebase

Okay, I will do that

**Comment by eliorerz** [comment]
I just noticed that you removed all the logic from your PR. Is that intent? 
If so, change the PR title and description.
Thanks

**Review by eliorerz — APPROVED** [review]

**Pull request merged**
