### PR TITLE
MGMT-3417 - infra changes for static ips e2e test

### PR DESCRIPTION
**Pull request by yevgeny-shnaidman**

### CODE REVIEW

**Comment by tsorya** [comment]
We need to add get ip functionality to e2e test in static ip mode, currently it will not work

**Comment by yevgeny-shnaidman** [comment]
> We need to add get ip functionality to e2e test in static ip mode, currently it will not work

i will open another a Jira ticket that will implement this functionality in terraform controller based on tfvars and ping

**Pull request merged**
