### PR TITLE
Add TEMP sleep before declaring that cluster is Ready

### PR DESCRIPTION
**Pull request by lalon4**

### CODE REVIEW

**Comment by YuviGold** [comment]
Why do we wait twice? To verify consistency?

**Comment by lalon4** [comment]
According to the failures we had, looks like between the wait_for_ready and start_install, some hosts are moving to insufficient. 
So need to make sure they are connected before start install otherwise test fails. 
This is TEMP solution, for now we need to understand if its a defect need to be fixed in the service or real machine connectivity issue

**Review by YuviGold — APPROVED** [review]

**Pull request merged**
