### PR TITLE
[release-ocm-2.4] MGMT-9102: always upgrade libgcrypt package using regular sources

### PR DESCRIPTION
**Pull request by eliorerz**
See https://github.com/openshift/assisted-test-infra/pull/1248 for more details

### CODE REVIEW

**Review by osherdp — APPROVED** [review]

**Comment by lranjbar** [comment]
Is this a case we need to override the failing test? It isn't building but unsure if that is because it is so far behind now that we had to rollback

**Comment by osherdp** [comment]
/hold
saving resources

**Comment by eliorerz** [comment]
This change will be merged with https://github.com/openshift/assisted-test-infra/pull/1431

**Pull request closed without merging**
