### PR TITLE
MGMT-1931 - default openshift version supported is now 4.6

### PR DESCRIPTION
**Pull request by yevgeny-shnaidman**

### CODE REVIEW

**Comment by YuviGold** [comment]
@yevgeny-shnaidman Both CIs failed on Installation TO. Maybe the new version installation takes more time?

**Comment by yevgeny-shnaidman** [comment]
@YuviGold no, this commit is part of general commits for 4.6. We will first push all the rest of the repositories with 4.6 commits, and after that Ci should path

**Pull request merged**
