### PR TITLE
NO-ISSUE: Add info to the raised exception instead of exception chaining

### PR DESCRIPTION
**Pull request by eliorerz**
/cc @osherdp

### CODE REVIEW

**Review by osherdp — APPROVED** [review]
PyCon already proofs useful :)

**Comment by eliorerz** [comment]
Exception seems ok 
```
waiting.exceptions.TimeoutExpired: Timeout of 3600 seconds expired waiting for Monitored ['builtin'] operators to be in of the statuses ['available']
Failed to deploy the following operators ['cvo']
```

**Pull request merged**
