### PR TITLE
MGMT-3684 Do not set machine CIDR in none-platform

### PR DESCRIPTION
**Pull request by rollandf**
- Do not set machine CIDR in none-platform
- Enable second network on SNO

### CODE REVIEW

**Comment by rollandf** [comment]
@tsorya

**Review by YuviGold — APPROVED** [review]

**Review by eranco74 — COMMENTED** [review]
/lgtm

**Comment by eranco74** [comment]
Worth mentioning that this is no longer relevant since the assisted-service will get the machine CIDR from the bootstrap node
https://github.com/openshift/assisted-service/pull/967

**Pull request merged**
