### PR TITLE
NO-ISSUE: Deploy assisted-image-service from prow

### PR DESCRIPTION
**Pull request by adriengentil**
We currently deploy the latest image of the assisted-image-service from
quay in minikube, regardless the branch we are in.

This change captures the depenpency on the assisted-image-service set by
Prow config.

### CODE REVIEW

**Comment by adriengentil** [comment]
For the context, you can see that in [this 2.5 job](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-cluster-api-provider-agent-release-ocm-2.5-e2e-capi-provider-hypershift-periodic/1541979484075331584/artifacts/e2e-capi-provider-hypershift-periodic/assisted-baremetal-gather/artifacts/k8s_events.log), we deploy the assisted-image-service from quay with the tag latest.

**Comment by omertuc** [comment]
You may want to run one of the tests above, if you think any of them are needed to verify your change. But maybe the default ones are already enough

**Review by osherdp — APPROVED** [review]

**Comment by omertuc** [comment]
```
2022-06-30T09:20:22.189817204Z {"file":"/go/src/github.com/openshift/origin/main.go:75","func":"main.main.func1","level":"fatal","msg":"Failed to populate image store: invalid version entry map[cpu_architecture:x86_64 openshift_version:4.6 url:https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-4.6.8-x86_64-live.x86_64.iso version:46.82.202012051820-0]: missing rootfs_url key\n","time":"2022-06-30T09:20:22Z"}
```

**Comment by adriengentil** [comment]
> ```
> 2022-06-30T09:20:22.189817204Z {"file":"/go/src/github.com/openshift/origin/main.go:75","func":"main.main.func1","level":"fatal","msg":"Failed to populate image store: invalid version entry map[cpu_architecture:x86_64 openshift_version:4.6 url:https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-4.6.8-x86_64-live.x86_64.iso version:46.82.202012051820-0]: missing rootfs_url key\n","time":"2022-06-30T09:20:22Z"}
> ```
> 
> From sosreport `sos_commands/podman/containers/podman_logs_-t_e489ed32c36a`

it is not related with this change, and was fixed with https://github.com/openshift/assisted-service/pull/4048

**Pull request merged**
