### PR TITLE
MGMT-1578 Adapt test-infra for pending-for-input state

### PR DESCRIPTION
**Pull request by ori-amizur**

### CODE REVIEW

**Comment by YuviGold** [comment]
Is that a new state? I don't see it on [bm-inventory/swagger.yaml][https://github.com/filanov/bm-inventory/blob/master/swagger.yaml)
If there's a PR - Please provide a link in the description

**Comment by ori-amizur** [comment]
> Is that a new state? I don't see it on [bm-inventory/swagger.yaml](https://github.com/filanov/bm-inventory/blob/master/swagger.yaml)
> If there's a PR - Please provide a link in the description

@YuviGold Please look at https://github.com/filanov/bm-inventory/pull/447

**Comment by ronniel1** [comment]
@YuviGold  This seems to have failed on a lint error, but I can not find which

**Comment by YuviGold** [comment]
> @YuviGold This seems to have failed on a lint error, but I can not find which

When linking on the details [link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-test-infra/51/pull-ci-openshift-assisted-test-infra-master-lint/1285472601019256832) you can see it fails on "black" linter
```bash
black....................................................................Failed
- hook id: black
- files were modified by this hook
```
Running `make lint` should fix it.

**Comment by ori-amizur** [comment]
> > @YuviGold This seems to have failed on a lint error, but I can not find which
> 
> When linking on the details [link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-test-infra/51/pull-ci-openshift-assisted-test-infra-master-lint/1285472601019256832) you can see it fails on "black" linter
> 
> ```shell
> black....................................................................Failed
> - hook id: black
> - files were modified by this hook
> ```
> 
> Running `make lint` should fix it.

@YuviGold @ronniel1 Fixed

**Pull request merged**
