### PR TITLE
Fix assets.py listAllNetworks

### PR DESCRIPTION
**Pull request by bkopilov**
In parallel tests we may get a list of all networks but testcase cleanup may delete the netowrk object from the test. We get here all libvirt network and we must consider case when one of the network no more available while we in the loop.

### CODE REVIEW

**Comment by bkopilov** [comment]
@eliorerz  , @lalon4

**Comment by bkopilov** [comment]
@adriengentil

**Comment by bkopilov** [comment]
The problem is that :
```
def DHCPLeases(self, mac=None, flags=0):
        """Returns a list of dhcp leases for interfaces connected to the given virtual network """
        ret = libvirtmod.virNetworkGetDHCPLeases(self._o, mac, flags)
        if ret is None:
            raise libvirtError('virNetworkGetDHCPLeases() failed')
        return ret
```

**Comment by bkopilov** [comment]
@eliorerz , @lalon4  ,

**Comment by bkopilov** [comment]
@osherdp

**Comment by adriengentil** [comment]
/test e2e-metal-assisted-day2-arm-workers
this job does some tricks to get libvirt network configuration

**Review by adriengentil — APPROVED** [review]

**Pull request merged**
